### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by Valentyn72** [Eren121/FairTrade#5]
Hi, this is "error console" : 

 `[Server thread/ERROR]: Could not pass event InventoryClickEvent to FairTrade v2.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2127) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.IllegalArgumentException: Negative, non outside slot -1
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.inventory.InventoryView.getInventory(InventoryView.java:216) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory(InventoryClickEvent.java:167) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at fr.rafoudiablol.ft.utils.APIListener.event(APIListener.java:18) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]`

**Comment by PapiCapi** [comment]
This error appears with spigot 1.13.2 and with the latest version (2.3 but it is showing 2.2 in logs)

**Comment by Eren121** [comment]
Hey, sorry for late response.
It can be a Spigot bug and be fixed. I am going to check it.
